### ISSUE TITLE
Add "The Past Web", particularly Jones et al.'s chapter relating to Memento

### ISSUE THREAD

**Issue by machawk1** [machawk1/awesome-memento#13]
Thread @ https://twitter.com/shawnmjones/status/1387430464869179395

@shawnmjones Will there be a version (e.g., preprint) freely available on the web? If not, we can just provide a link (e.g., https://www.springer.com/gp/book/9783030632908) to reference once released (presumably July 6, 2021).

**Comment by shawnmjones** [comment]
I don't know. I will have to consult the editors. This is the first book chapter I've collaborated on. :-)

**Comment by machawk1** [comment]
That is one more than me, @shawnmjones. Perhaps @phonedude knows whether there is (or traditionally is) an intention to publish a freely available version for further dissemination.
